name: Smart Contracts Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: npx hardhat test --network hardhat
        env:
          INFURA_PROJECT_ID: '9a22fd6b68e941aa91a9df7258be9853'
          RINKEBY_GAS_PRICE: '5500000000'
          RINKEBY_UNISWAP_ROUTER_ADDR: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D'
